version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '1935:1935'
      - '8000:8000'
    volumes:
      - ./media:/usr/src/app/media
      - ./db:/usr/src/app/db
    environment:
      - PORT=3000
      - RTMP_PORT=1935
      - HLS_HTTP_PORT=8000
      - JWT_SECRET=replace-with-secret
      - SESSION_SECRET=replace-session-secret
